sudo:required
services:
  - docker

before_install:
  - docker build -t arrrsh/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run arrrsh/react-test npm test -- --coverage

after_success:
  - docker build -t arrrsh/multi-client ./client
  - docker build -t arrrsh/multi-nginx ./nginx
  - docker build -t arrrsh/multi-server ./server
  - docker build -t arrrsh/multi-worker ./worker
  # Log in to the docker CLI, DOCKER_PASSWORD and DOCKER_ID are defined in travis-ci.com
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push arrrsh/multi-client
  - docker push arrrsh/multi-nginx
  - docker push arrrsh/multi-server
  - docker push arrrsh/multi-worker
