language: generic
services:
  - docker

before_install:
  - docker build -t arrrsh/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true arrrsh/react-test npm test
  # - docker run arrrsh/react-test npm test -- --coverage

after_success:
  - docker build -t arrrsh/multi-client ./client
  - docker build -t arrrsh/multi-nginx ./nginx
  - docker build -t arrrsh/multi-server ./server
  - docker build -t arrrsh/multi-worker ./worker
  # Log in to the docker CLI, DOCKER_PASSWORD and DOCKER_ID are defined in travis-ci.com
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push arrrsh/multi-client
  - docker push arrrsh/multi-nginx
  - docker push arrrsh/multi-server
  - docker push arrrsh/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-eu-west-1-151561624340
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY